bob-collective/bob

src/swap/Btc_Marketplace.sol

Changing bitcoin address type to string so we can easily store it.

refactor: change bitcoin address type to string

---

.gitmodules
foundry.toml
src/bridge/BitcoinTx.sol
src/bridge/BridgeState.sol
src/bridge/IRelay.sol
src/relay/LightRelay.sol
test/LightRelay.t.sol

Forked from https://github.com/keep-network/tbtc-v2

Add light-relay code from tbtc-v2

---

src/bridge/WitnessTx.sol
test/BitcoinTx.t.sol
test/WitnessTx.sol

To check witness data is actually valid according to the relay:
1. verify coinbase is included (tx + merkle proof)
2. verify payment is included (tx + merkle proof)
3. validate witness commitment (extract root from coinbase, provide merkle proof for wtxids)
We can use this in the future to verify witness inscriptions, actually the tests already use the BRC20 deploy tx so the next step is to parse the ordinal data.

feat: add contract and tests to check witness proof

---

sdk/src/electrs.ts

Required for building apps with browser-based wallets that only support signing (i.e. the MetaMask snap). We need to do the following things to be able to send Bitcoin:
1. Get addresses from wallet
2. List UTXOs available to spend using Electrs - **this is what this PR adds**
3. Fund transaction (provide those inputs and specify outputs)
4. Sign transaction with wallet and send using Electrs
I would also recommend using a coin selection library such as [coinselect](https://github.com/bitcoinjs/coinselect).

feat: add electrs method to fetch utxos

---

README.md

Docusaurus tries to link `init-bridge.ts` if it's a relative path hence the absolute GitHub URL used in readme.

fix: Docusaurus broken link.

---

src/swap/Btc_Marketplace.sol

This PR is a quick fix to unblock other PRs
PR #97 was merged despite failing CI, 
CI error:
```
Error: Fatal: No URL found for submodule path 'contracts/hello-zkvm' in .gitmodules
Error: The process '/usr/bin/git' failed with exit code 128
```
The submodule should be included under the `lib` directory with a valid Acurast repository if we intend to add the submodule.

fix: remove contracts dir

---

src/swap/Ord_Marketplace.sol
test/swap/Ord_Marketplace.t.sol

The PR makes the following changes
- Add `index` field in the Ordinal struct
- Add `isOrderAccepted` field, along with testcase
- Add `todo` in `proofOrdinalSellOrder`
- Clears storage when required

fix: bugs in ordinal marketplace contract

---

docker-compose.yml
docs/docs/contracts/src/src/relay/LightRelay.sol/contract.LightRelay.md
src/relay/LightRelay.sol

fix: Update btc core version, add docs to relay contract

---

.github/workflows/test.yml
foundry.toml

The `viaIR` flag is currently disabled during the build process, leading to a compiler error. You can check the error [here](https://github.com/bob-collective/bob/actions/runs/7828910688/job/21359772350#step:5:10). It's recommended to enable this flag by default to avoid build errors.
Note: It doesn't add any security vulnerabilities, just a semantic change.

fix: compile contract with viaIR flag .

---

docs/docs/build/getting-started/networks.md

Based on Caldera redeploy after Sander caught the old EVM version on the previous testnet.

Update testnet info (chain ID 606808)

---

docs/docs/build/getting-started/networks.md

@nud3l, I left the https version of the RPC URL because it works correctly for the most common use-case, adding a network to a wallet. I'm not sure what the websocket version would be used for, but Nikolai helped verify this version (trailing /wss) works. 
If you'd like to list the websocket version of the RPC (alongside the https version) approve this PR.

Add websocket link to network page

---

docs/docs/build/bob-sdk/relay.md
docs/docs/contracts/src/src/utils/BitcoinTx.sol/library.BitcoinTx.md
sdk/test/relay.test.ts
src/swap/Btc_Marketplace.sol
src/swap/Ord_Marketplace.sol
src/utils/BitcoinTx.sol
test/BitcoinTx.t.sol

So we can specify the recipient EVM address in the Bitcoin transaction

feat: extract evm address from op return

---

docs/docs/build/getting-started/index.md
docs/docs/build/getting-started/local-development.md
docs/docs/build/tools/account-abstraction.md
docs/docs/build/tools/api.md
docs/docs/build/tools/bonsai.md
docs/docs/build/tools/data-indexers.md
docs/docs/build/tools/nfts-ordinals.md
docs/docs/build/tools/oracles.md
docs/docs/build/tools/rust-zkvm.md
docs/docs/build/tools/wallets.md

@nud3l I'm trying to balance getting information we do have for tools that are live out ASAP with waiting for complete information. Here's everything I know from everyone that is committed.
Please review the names of each provider to catch if I've included anyone prematurely. In some cases (e.g. API3) I've intentionally added information before the partner is live on BOB. Totally open to feedback here.

Add Tools to docs

---

docs/docs/learn/guides/bob-fusion.md
docs/docs/learn/introduction/contribution.md
docs/docs/learn/introduction/use-cases.md

This adds several callouts on relevant docs pages for builders to contact us. If we want something like this to be even more visible, we could consider a CTA in the header of all pages.
@nud3l, do you think a "Join Fusion" link next to Discord and GitHub in the header is too prominent, potentially leading to spam for Chris?

Add CTA links for builders to connect with BD

---

sdk/examples/gateway.ts
sdk/package-lock.json
sdk/package.json
sdk/scripts/relay-genesis.ts
sdk/scripts/relay-retarget.ts
sdk/src/esplora.ts
sdk/src/gateway.ts
sdk/src/helpers.ts
sdk/src/index.ts
sdk/src/inscription.ts
sdk/src/ordinal-api/index.ts
sdk/src/relay.ts
sdk/src/utils.ts
sdk/src/wallet/address.ts
sdk/src/wallet/index.ts
sdk/src/wallet/inscriptions.ts
sdk/src/wallet/utxo.ts
sdk/test/esplora.test.ts
sdk/test/inscription.test.ts
sdk/test/ordinal-api.test.ts
sdk/test/relay.test.ts
sdk/test/utils.test.ts
sdk/test/utxo.test.ts
sdk/tsconfig.json

refactor: import gateway client and updated wallet logic

---

docs/docs/build/bob-sdk/gateway.md
docs/docs/build/bob-sdk/relay.md
docs/docs/learn/guides/bitcoin-bridge/index.md

Adds a new page to the `BOB SDK` section of the `Build` docs that briefly explains BOB Gateway and provides a step-by-step integration tutorial based on [/sdk/examples/gateway.ts](https://github.com/bob-collective/bob/blob/master/sdk/examples/gateway.ts).
Steps only work after our GitHub actions upgrade [our npm package](https://www.npmjs.com/package/@gobob/bob-sdk?activeTab=versions) to 1.3.0, adding the Gateway API to the package.

docs: create step-by-step guide for gateway SDK

---

Dockerfile
sdk/src/scripts/relay-retarget.ts

Include Solidity scripts in the Docker image.

relay-retarget script

---

sdk/package.json
sdk/src/gateway/client.ts
sdk/test/gateway.test.ts

Allows `getQuote` to be used also to get the total liquidity

feat: optional amount for quote total

---

docs/docs/build/how-to/full-node.md

The previous version of this page had a broken link, leading to time wasted helping node-runners get set up.
Rather than track a moving target (i.e. maintain our own version of Conduit's and Optimism's steps for running a BOB node), we point to their resources and update links when necessary.

docs: Replace broken Conduit link with guides

---

docs/docs/build/getting-started/index.md

Small PR to add the Gateway SDK page to an unordered list it was missing from.

docs: Add Gateway to SDK list on Getting Started

---

sdk/README.md
sdk/src/gateway/client.ts
sdk/src/gateway/types.ts
sdk/src/utils.ts
sdk/src/wallet/utxo.ts
sdk/test/esplora.test.ts
sdk/test/ordinal-api.test.ts
sdk/test/utils.test.ts
sdk/test/utxo.test.ts

Instead of relying on assumptions about the inputs, allow fee estimation to account for all possible inputs.

Better fee estimation

---

sdk/package.json
sdk/src/esplora.ts

Reverts bob-collective/bob#390

Revert "feat: add confirmed param to esplora getBalance"

---

docs/docs/build/how-to/safe-gas-station.md

A page for the Safe team to share with builders when referencing BOB's part in the [Safe{CORE} Gas Station](https://safe.global/gas-station) program.

Create landing page for Safe Gas Station campaign

---

docs/docusaurus.config.js

This PR adds redirects for recently moved docs pages during #382, fixing `404` broken links where possible. In that PR some pages were deleted; no redirects were added for those.
Preview deployment example:
- [/docs/build/getting-started/networks](https://bob-fkbg0563c-distributed-crafts.vercel.app/docs/build/getting-started/networks) redirects to [/learn/user-guides/networks](https://bob-fkbg0563c-distributed-crafts.vercel.app/learn/user-guides/networks)

Add redirects for moved docs pages

---

docs/docs/learn/reference/research.md

Add a missing paper (i.e. BitVM) to the new Research page in our docs.

Add BitVM paper to Research page

---

sdk/package.json
sdk/src/wallet/utxo.ts
sdk/test/utxo.test.ts

Also includes updates to 
- estimateTxFee
- createBitcoinPsbt
⚠️ Inputs that contain ordinals or runes no longer will be used in tx fee estimations or could be spent from (any, not just taproot) address

Add balance calculation logic

---

docs/docs/learn/reference/tools/oracles.md
docs/docs/learn/reference/tools/rust-zkvm.md

In Issue #423 there's reference to 4 broken links in the documentation which needed fixing. In summary this is how I've fixed them 
1.  The first link was in reference to `first party oracles` and referred to the Airnode API docs. I found the new section in airnode's API docs which discuss and give context for first party oracles.
2. The second broken link was in reference to `OEV Recapture` and was also a link to Airnode's API docs. I found a new section in their docs which discusses and gives context for this topic under a more generalized heading.
3. This hyperlink was to direct users on how to fund their metamask wallet on a testnet. I've replaced it with a link to the page from Metamask's own documentation on how to fund a Metamask wallet on a testnet.
4. This link was previously to …

Fix broken links in docs (Issue #423)

---

docs/docs/learn/builder-guides/bridged-btc-gas-fee/account-abstraction/index.md

The previous link to Pimlico's site was a Notion page they have since deprecated. Now it points to their main docs site, https://docs.pimlico.io/

chore: fix broken external link

---

docs/docs/learn/builder-guides/full-node.md

Closes #428 by adding upgrade information in advance of January 9th's Holocene upgrade to our network.

docs: add Holocene upgrade info

---

README.md

Updates the calculation from $9M to $12M based on current difficulty and total hashrate.

chore: update Light Relay attack cost

---

docs/docs/learn/builder-guides/metamask-snap.md
docs/docusaurus.config.js

Bring back the MM Snap page.
Remove links to the live demo, which is no longer hosted. 
Update language to suggest a curious dev can run the app locally.
Add a redirect from the previous page location, fixing the broken `Knowledge Base` link on our [MM Snap page](https://snaps.metamask.io/snap/npm/gobob/bob-snap/).

docs: bring back the MetaMask Snap page

---

docs/docs/learn/builder-guides/bridged-btc-gas-fee/account-abstraction/index.md

This PR updates the [ERC-4337 demo page](https://docs.gobob.xyz/learn/builder-guides/bridged-btc-gas-fee/account-abstraction/) in light of our deprecation of the corresponding live demo ([GH repo](https://github.com/bob-collective/demo-account-abstraction-transfer/)).
The most important diff is under `Connecting MetaMask and funding your account`, where I updated the steps to assume the user is running the FE locally. Our bridge app has long since switched to mainnet (woohoo), so I point to the Superbridge specific to _old_ testnet for the "bridging sepETH" step.

docs: rework AA page without live demo

---

docs/docusaurus.config.js
docs/static/robots.txt

Improve the search experience on our docs pages by switching from native Docusaurus search to Algolia.
[Docusaurus has first-class support for Algolia](https://docusaurus.io/docs/search#using-algolia-docsearch), so this implementation relies on the default config. 
- The notable option is `insights: true`, which helps us see common searches and results. For example, this can help us discover if users are searching for a page that does not exist yet.
We can view this data and manage our Algolia account from [their dashboard](https://dashboard.algolia.com/apps/AO8XE1SP27/dashboard). Login details to follow privately.
Example of search UI:
Example of `docs.gobob.xyz/search` page:
Also including a small commit for formatting lines 186-190, just to get it out of the way.

feat: add algolia search to docs

---

docs/docusaurus.config.js

Adds an external link in the docs header to a [Status Page](https://conduit-bob.checkly-dashboards.com/) for BOB Mainnet and Sepolia.
Docs Header Bar
Status Page
I've asked Conduit whether it's possible to query the underlying API (Checkly) so we can provide a status preview icon next to the word `Status`. Example:

docs: add Status Page link to header

---

sdk/src/wallet/utxo.ts
sdk/test/utxo.test.ts

(untested) wrap in a recursive function

refactor: simplify wallet ord logic

---

docs/docs/learn/user-guides/networks.md

OP recently added a BOB Sepolia faucet to their docs. This adds an external link to that faucet within our Network page.
I have not been able to get [the faucet](https://console.optimism.io/faucet) to work; please try it yourself before merging.

docs: add OP's faucet for BOB Sepolia to Network page
