bob-collective/bob

docs/docusaurus.config.js
Most of these changes are automatic linting. The only actual code change is the plugins config at L36.
=> [feature] Add tracking script

.gitmodules, contracts/bridge/.gitignore, contracts/bridge/README.md, contracts/bridge/foundry.toml, contracts/bridge/remappings.txt, contracts/bridge/script/bridge.s.sol, contracts/bridge/src/bridge.sol, contracts/bridge/src/btc_marketplace.sol, contracts/bridge/src/marketplace.sol, contracts/bridge/src/wrapped.sol, contracts/bridge/test/bridge.t.sol, contracts/bridge/test/btc_marketplace.t.sol, contracts/bridge/test/marketplace.t.sol, contracts/bridge/test/utils/Console.sol, contracts/bridge/test/utils/Utilities.sol
=> feat: initial bridge draft with lots of todos

sdk/package.json, sdk/src/electrs.ts, sdk/src/relay.ts, sdk/src/utils.ts, sdk/test/electrs.test.ts, sdk/test/relay.test.ts, sdk/test/utils.test.ts, sdk/tsconfig.json
Initialize bob-sdk, get merkle proof via electrs and encode correctly for relay
=> Add bob typescript sdk

src/bridge/BitcoinTx.sol, test/BitcoinTx.t.sol
Should be used by the p2p swap contract to verify the output amount
=> feat: add tx output value extraction

src/swap/Btc_Marketplace.sol, test/swap/Btc_Marketplace.t.sol
Note that nothing is being done with the arguments yet
=> feat: take proof and tx as argument

sdk/src/electrs.ts
=> fix: change testnet and mainnet urls

docs/docs/build/examples/demo_unified_assets_tracker/index.md
Adding docs page for Unified Assets Tracker demo.
=> docs: add example page for unified assets hackathon demo

docker-compose.yml, docs/docs/build/how-to/bitcoin-testing.md
Before working on https://github.com/bob-collective/bob/issues/54 we have decided to get feedback from existing Bitcoin builders. In the meantime we can better explain how to use the docker-compose setup or more complete tooling like [Nigiri](https://github.com/vulpemventures/nigiri/).
=> docs: add regtest explainer

README.md, docker-compose.yml, sdk/scripts/init-bridge.ts
Next step is to provide additional scripts and instructions to deploy the P2P swap POC
=> feat: add anvil to docker-compose and reconfigure deploy script

docs/docs/build/contracts/index.md, docs/docs/build/examples/brc20-octopus/index.md, docs/docs/build/examples/unified-assets-tracker/index.md, docs/docs/build/getting-started/index.md, docs/docs/build/how-to/bridged-btc-gas-fee/account-abstraction/index.md, docs/docs/build/how-to/relay.md, docs/docs/build/tools/api.md, docs/docs/drafts/roadmap.md, docs/docs/drafts/stack.md
Some text corrections and link updates.
=> docs: Texts corrections

.github/workflows/test.yml, docs/docs/build/tools/wallets.md, docs/docs/contracts/src/src/TestingErc20.sol/contract.TestingErc20.md, docs/docs/contracts/src/src/bridge/BitcoinTx.sol/library.BitcoinTx.md, docs/docs/contracts/src/src/bridge/BridgeState.sol/library.BridgeState.md, docs/docs/contracts/src/src/bridge/IRelay.sol/interface.IRelay.md, docs/docs/contracts/src/src/bridge/WitnessTx.sol/library.WitnessTx.md, docs/docs/contracts/src/src/faucet/Erc20Minter.sol/contract.Erc20Minter.md, docs/docs/contracts/src/src/faucet/Erc20Minter.sol/interface.Erc20Mintable.md, docs/docs/contracts/src/src/paymasters/AccountAbstraction/AATokenPaymaster.sol/contract.PimlicoERC20Paymaster.md, docs/docs/contracts/src/src/paymasters/AccountAbstraction/SafeTransferLib.sol/library.SafeTransferLib.md, docs/docs/contracts/src/src/paymasters/OnboardingPaymaster.sol/contract.OnboardingPaymaster.md, docs/docs/contracts/src/src/paymasters/Oracle.sol/contract.DummyOracle.md, docs/docs/contracts/src/src/paymasters/Oracle.sol/interface.IOracle.md, docs/docs/contracts/src/src/paymasters/OracleTokenPaymaster.sol/contract.OracleTokenPaymaster.md, docs/docs/contracts/src/src/relay/LightRelay.sol/contract.LightRelay.md, docs/docs/contracts/src/src/relay/LightRelay.sol/interface.ILightRelay.md, docs/docs/contracts/src/src/relay/LightRelay.sol/library.RelayUtils.md, docs/docs/contracts/src/src/relay/LightRelay.sol/struct.Epoch.md, docs/docs/contracts/src/src/relay/TestLightRelay.sol/contract.TestLightRelay.md, docs/docs/contracts/src/src/swap/Bridge.sol/contract.Bridge.md, docs/docs/contracts/src/src/swap/Btc_Marketplace.sol/contract.BtcMarketPlace.md, docs/docs/contracts/src/src/swap/Faucet.sol/contract.Faucet.md, docs/docs/contracts/src/src/swap/Faucet.sol/interface.Erc20Mintable.md, docs/docs/contracts/src/src/swap/Marketplace.sol/contract.MarketPlace.md, docs/docs/contracts/src/src/swap/Ord_Marketplace.sol/contract.OrdMarketplace.md, docs/docs/contracts/src/src/swap/Wrapped.sol/contract.BobWrappedBtc.md
**Problem**
Running `forge doc` command is failing for PRs, check [job](https://github.com/bob-collective/bob/actions/runs/7282781272/job/19845682792#step:7:9) 
**Solution** 
Revert back Foundry to the previous version until the `forge doc` issue is resolved. 
[Issue raised](https://github.com/foundry-rs/foundry/issues/6642) on foundry
=> chore: Fix forge generated docs

.github/workflows/test.yml
Foundry doc Issue resolved in [PR 6644](https://github.com/foundry-rs/foundry/pull/6644). So can set back the version to nightly.
=> fix: set foundry version to latest nightly.

test/BitcoinTx.t.sol, test/LightRelay.t.sol, test/swap/Ord_Marketplace.t.sol
- Adds test cases for bitcoin utils
=> fix: testcases for bitcoin utils.

src/paymasters/AccountAbstraction/AATokenPaymaster.sol
The PR 
- It removes unchecked from the paymaster contract, making safe math operations the default.
- It's worth noting that this change may lead to increased gas consumption compared to using unchecked.
=> fix: remove unchecked from contract.

docs/docs/build/getting-started/helloworld.mdx
The Pr does the following. 
- Closes #159. 
- display `foundry` tab as primary, reasons
- `starterkit` in foundry.  
- all of bob repos developed with foundry. 
- Create separate remix and foundry tabs for verifying smart contract
=> docs: Update hello bitcoin guide

sdk/src/inscription.ts, sdk/src/ordinal-api/index.ts, sdk/src/ordinals/commit.ts, sdk/src/ordinals/index.ts, sdk/test/inscription.test.ts, sdk/test/ordinal-api.test.ts, sdk/test/ordinals.test.ts
- put all inscription logic in one place
- fix ord client for latest version
=> refactor: inscription class

script/RelayGenesis.s.sol, script/RelayRetarget.s.sol, sdk/package-lock.json, sdk/package.json, sdk/scripts/relay-genesis.ts, sdk/scripts/relay-retarget.ts
Adds a script to automatically submit the relay retargets
=> feat: add script to do relay retargets

docs/docs/build/bob-sdk/bridged-btc-gas-fee/account-abstraction/index.md, docs/docs/build/bob-sdk/bridged-btc-gas-fee/meta-transactions/index.md, docs/docs/build/bob-sdk/metamask-snap.md, docs/docs/build/contracts/index.md, docs/docs/build/examples/btc-swap/index.mdx, docs/docs/build/examples/metamask-ordinals/index.md, docs/docs/build/examples/unified-assets-tracker/index.md, docs/docs/build/getting-started/helloworld.mdx, docs/docs/build/getting-started/networks.md, docs/docs/learn/guides/index.md
This PR provides the updated URLs for the BOB testnet. It updates the demo pages to with warnings about our testnet change.
=> docs: add Caldera info, update demo pages with warnings

.gitignore, README.md, script/RelayGenesis.s.sol, script/RelayRetarget.s.sol, sdk/package.json, sdk/scripts/relay-genesis.ts, sdk/scripts/relay-retarget.ts, sdk/src/electrs.ts, test/swap/Btc_Marketplace.t.sol, test/swap/Ord_Marketplace.t.sol
Cleanup the relay deployment / retarget scripts, add contract details to readme
=> refactor: better relay scripts

docs/docs/build/bob-sdk/metamask-snap.md, docs/docs/build/examples/btc-swap/index.mdx, docs/docs/build/examples/metamask-ordinals/index.md, docs/docs/build/examples/unified-assets-tracker/index.md, docs/docs/build/how-to/ordinals.md, docs/docs/build/tools/wallets.md
@nud3l this can go live immediately; doesn't need to wait for mainnet launch.
=> Remove mentions of Flask from Snap page

docs/docs/build/bob-sdk/_category_.yml, docs/docs/build/contracts/_category_.yml, docs/docs/build/tools/_category_.yml, docs/docs/build/tools/oracles.md
=> Add DIA addresses, adjust sidebar

README.md
Provide some more context on the security of the light relay
=> docs: review security of relay

docs/docs/build/tools/oracles.md
used the correct link for our integration guide and changed the about blurb.
=> Update Tellor section in oracles.md 

docs/docs/build/getting-started/networks.md, docs/docs/build/tools/node-providers.md, docs/docs/build/tools/oracles.md, docs/docs/build/tools/social-login.md
Add BlastAPI RPCs to Network page.
Create Node Providers page with BlastAPI, Conduit, and Tenderly.
Create Social Login page for Arcana Auth.
Update DIA oracle info.
=> Add node providers, BlastAPI RPC, and other tools

docs/docs/build/tools/oracles.md
Updated API3 docs content and Market links for [Bob Mainnet](https://market.api3.org/bob) and [Bob Sepolia Testnet](https://market.api3.org/bob-sepolia-testnet)
=> Update API3 docs under Oracles

docs/docusaurus.config.js
Small tweak to our docs config for future-proofing certain errors at build time
=> Add checks for broken anchors and duplicate routes

docs/docs/learn/bob-stack/op-stack.md
The full version with docs copied from optimism
=> add info on the fraud proof changes

docs/docs/build/bridged-token-addresses/index.md, docs/docs/build/contracts/index.md, docs/docs/build/getting-started/networks.md, docs/docs/build/tools/oracles.md, docs/docs/learn/guides/use-bob.md
Need to get DIA and Tellor to re-deploy
=> feat: add new bob-sepolia testnet info

docs/docs/build/tools/data-indexers.md
Please add SQD to your tools/data-indexers page. We have been supporting Bob for some time - https://docs.subsquid.io/subsquid-network/reference/evm-networks/.
=> Add SQD to Tools

sdk/examples/gateway.ts
Previously requested in [PR comment](https://github.com/bob-collective/bob/pull/312#discussion_r1715482053)
=> chore: add back gateway example todo

sdk/examples/gateway.ts, sdk/src/gateway/client.ts, sdk/src/gateway/tokens.ts, sdk/src/gateway/types.ts
Also update example and return types
=> feat: add doc comments to gateway v3 sdk

docs/docs/build/bob-sdk/gateway.md, docs/docs/build/bob-sdk/sats-wagmi.md, docs/docusaurus.config.js, docs/package.json, sdk/src/esplora.ts, sdk/src/gateway/client.ts, sdk/test/gateway.test.ts
Mostly copied the structure from here: https://wagmi.sh/react/guides/connect-wallet
Although I noticed this was a copy-paste from the sats-wagmi README, perhaps we should keep the docs there and link?
=> docs: update sats-wagmi

docs/docs/learn/guides/bob-gateway/index.md, docs/docs/learn/introduction/contribution.md
Changes `gateway [ at ] gobob.xyz` to `gateway@gobob.xyz` on two pages.
=> Remove bot crawling protection from email addresses

sdk/package-lock.json, sdk/package.json, sdk/src/gateway/client.ts, sdk/src/gateway/tokens.ts, sdk/src/gateway/types.ts, sdk/test/gateway.test.ts
Better prepare for consuming the token list, fixes the token amount if e.g. using tBTC
=> refactor: separate tokens, get token amount

docs/docs/learn/guides/bob-fusion/index.md
Updates a specific docs page with Season 3 information.
Changes to the order of sections (especially FAQ) make the diff look weirder than it is.
Please sanity-check the preview deployment, then :shipit:
=> Update Fusion page with Season 3 info

sdk/package.json
Reverts bob-collective/bob#383
=> Revert "chore: bump version"

sdk/src/wallet/utxo.ts
- if `amount` is `undefined`, it spends all inputs.
- if `amount` is defined, it spends only the inputs required to send the amount. If an amount is specified that is more than than we can spend, an error is thrown
=> fix: fee estimate

docs/docs/learn/builder-guides/full-node.md
Quick update to the [Full Node guide](https://docs.gobob.xyz/learn/builder-guides/full-node) based on recent Q&A w/ Conduit
=> chore: add Sepolia flags for holocene upgrade

docs/docs/learn/reference/tools/cross-chain.md
Add Chainlink to our cross-chain docs section.
=> docs: add Chainlink CCIP
